# nodeLinker: node-modules
# npmScopes:
#   bitslinger21:
#     npmRegistryServer: "https://npm.pkg.github.com"
#     npmAlwaysAuth: true
#     npmAuthToken: "${AUTH_TOKEN}"

nodeLinker: node-modules

npmScopes:
  bitslinger21:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmAlwaysAuth: true

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${AUTH_TOKEN}"
