set dotenv-load

default:
  @just --list

init-repo:
  cp -n .env.example .env

# generate-client:
#   mkdir -p generated/client/typescript-axios
#   touch generated/client/typescript-axios/yarn.lock
#   # docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.1 generate \
#   docker run --rm -v "${PWD}:/local" -e YARN_ENABLE_IMMUTABLE_INSTALLS=false openapitools/openapi-generator-cli:v6.2.1 generate \
#     -i /local/generated/openapi.yaml \
#     -g typescript-axios \
#     -o /local/generated/client/typescript-axios \
#     -c /local/generated/client/typescript-axios/generatorConfig.yml \

#   # Ensure tsconfig.json exists for the generated client (needed by `yarn build`)
#   cd generated/client/typescript-axios && \
#     echo '{"compilerOptions":{"declaration":true,"esModuleInterop":true,"module":"commonjs","outDir":"dist","strict":true,"target":"es2015"},"include":["./**/*.ts"],"exclude":["node_modules","dist"]}' > tsconfig.json && \
#     jq '.scripts.build="tsc -p ./tsconfig.json" | .scripts.prepublishOnly="yarn build"' package.json > package.tmp && \
#     mv package.tmp package.json && \
#     YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install && yarn build && \
#     find . -type f -name "*.ts" -not -path "./node_modules/*" -exec sed -i '' '/ \* The version of the OpenAPI document: .*/d' {} \;;

generate-client:
  rm -rf generated/client/typescript-axios
  mkdir -p generated/client/typescript-axios
  touch generated/client/typescript-axios/yarn.lock

  docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.1 generate \
    -i /local/generated/openapi.yaml \
    -g typescript-axios \
    -o /local/generated/client/typescript-axios

  cd generated/client/typescript-axios && \
    YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install && \
    find . -type f -name "*.ts" -not -path "./node_modules/*" -exec sed -i '' '/ \* The version of the OpenAPI document: .*/d' {} \;;
    